<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>VoucherPool</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link href='css/bootstrap.css' rel='stylesheet' type='text/css'>
        <link href='css/style.less' rel='stylesheet/less' type='text/css'>
        <link rel="stylesheet" href="https://unpkg.com/ag-grid/dist/styles/ag-grid.css">
        <link rel="stylesheet" href="https://unpkg.com/ag-grid/dist/styles/ag-theme-balham.css">
    </head>
    <body class="wrapper">
            <div class="container mb-4">
                <div class="row">
                    <div class="col-md-12">
                        <h1 class="mt-4 mb-4 text-center">
                            VanHack Test - VoucherPool
                        </h1>
                        <div class="row">
                            <div class="col-md-4">
                            </div>
                            <div class="col-md-4">
                            </div>
                            <div class="col-md-4">
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="container mb-4">
                <div class="row">
                    <div class="col-md-6">                        
                        <form role="form"  id="form-save-voucher" method="post" action="/voucher/save">
                            <div class="form-group">
                                <legend> Test Voucher Creation</legend>
                                
                                <label for="code">Recipient E-mail</label>
                                <input type="text" require class="form-control" name="email" placeholder="email@email.com;email1@email.com;email2@email.com"/>

                                <label for="name">Offer</label>
                                <input type="text" required class="form-control" name="name" />

                                <label for="name">Expiration Date</label>
                                <input type="text" required class="form-control" name="expires_at" />

                                <label for="discount">Discount</label>
                                <input type="text" required class="form-control" name="discount" />
                            </div>

                            <button type="submit" required  class="btn btn-primary">
                                Create Vouchers
                            </button>
                        </form>
                    </div>

                    <div class="col-md-6">                   
                        <form role="form" id="form-use-voucher" method="post" action="/voucher/use">
                            <div class="form-group">
                                <legend>Test Voucher Usage</legend>
                                
                                <label for="code">E-mail</label>
                                <input type="email" require class="form-control" name="email" />

                                <label for="code">Voucher Code</label>
                                <input type="text" required class="form-control" name="code" />
                            </div>

                            <button type="submit" class="btn btn-primary">
                                Use Voucher
                            </button>
                        </form>
                    </div>
                </div>
            </div>

            <div class="container">                
                <div class="row">
                    <div class="col-md-12">
                        <div id="voucher_list" class="ag-theme-balham"  data-endpoint="/vouchers">                        
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <ul class="bg-bubbles">
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
        </ul>

        <script src="//cdnjs.cloudflare.com/ajax/libs/less.js/3.7.1/less.min.js" ></script>        
        <script src="https://unpkg.com/ag-grid/dist/ag-grid.min.noStyle.js"></script>
        <script src="/js/events.js"></script>
    </body>
</html>
